// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Inventory struct {
	Sku                  string             `json:"sku"`
	MedicineName         string             `json:"medicine_name"`
	Quantity             int32              `json:"quantity"`
	RequiresPrescription bool               `json:"requires_prescription"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
