// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createInventoryItem = `-- name: CreateInventoryItem :one
INSERT INTO inventory (sku, medicine_name, quantity, requires_prescription)
VALUES ($1, $2, $3, $4)
RETURNING sku, medicine_name, quantity, requires_prescription, created_at, updated_at
`

type CreateInventoryItemParams struct {
	Sku                  string `json:"sku"`
	MedicineName         string `json:"medicine_name"`
	Quantity             int32  `json:"quantity"`
	RequiresPrescription bool   `json:"requires_prescription"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventoryItem,
		arg.Sku,
		arg.MedicineName,
		arg.Quantity,
		arg.RequiresPrescription,
	)
	var i Inventory
	err := row.Scan(
		&i.Sku,
		&i.MedicineName,
		&i.Quantity,
		&i.RequiresPrescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInventoryItem = `-- name: DeleteInventoryItem :exec
DELETE FROM inventory WHERE sku = $1
`

func (q *Queries) DeleteInventoryItem(ctx context.Context, sku string) error {
	_, err := q.db.Exec(ctx, deleteInventoryItem, sku)
	return err
}

const getInventoryItem = `-- name: GetInventoryItem :one
SELECT sku, medicine_name, quantity, requires_prescription, created_at, updated_at FROM inventory WHERE sku = $1
`

func (q *Queries) GetInventoryItem(ctx context.Context, sku string) (Inventory, error) {
	row := q.db.QueryRow(ctx, getInventoryItem, sku)
	var i Inventory
	err := row.Scan(
		&i.Sku,
		&i.MedicineName,
		&i.Quantity,
		&i.RequiresPrescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inventoryItemExists = `-- name: InventoryItemExists :one
SELECT EXISTS (SELECT 1 FROM inventory WHERE sku = $1)
`

func (q *Queries) InventoryItemExists(ctx context.Context, sku string) (bool, error) {
	row := q.db.QueryRow(ctx, inventoryItemExists, sku)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listLowStockItems = `-- name: ListLowStockItems :many
SELECT sku, medicine_name, quantity, requires_prescription, created_at, updated_at FROM inventory WHERE quantity < $1 ORDER BY quantity ASC
`

func (q *Queries) ListLowStockItems(ctx context.Context, quantity int32) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listLowStockItems, quantity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.Sku,
			&i.MedicineName,
			&i.Quantity,
			&i.RequiresPrescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventoryItem = `-- name: UpdateInventoryItem :one
UPDATE inventory
SET medicine_name         = $2,
    quantity              = $3,
    requires_prescription = $4,
    updated_at            = NOW()
WHERE sku = $1
RETURNING sku, medicine_name, quantity, requires_prescription, created_at, updated_at
`

type UpdateInventoryItemParams struct {
	Sku                  string `json:"sku"`
	MedicineName         string `json:"medicine_name"`
	Quantity             int32  `json:"quantity"`
	RequiresPrescription bool   `json:"requires_prescription"`
}

func (q *Queries) UpdateInventoryItem(ctx context.Context, arg UpdateInventoryItemParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, updateInventoryItem,
		arg.Sku,
		arg.MedicineName,
		arg.Quantity,
		arg.RequiresPrescription,
	)
	var i Inventory
	err := row.Scan(
		&i.Sku,
		&i.MedicineName,
		&i.Quantity,
		&i.RequiresPrescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
